//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN
    {
        public string MaDA { get; set; }
        public string TenDA { get; set; }
        public string DiaDiem { get; set; }
        public string MaPB { get; set; }
    
        public virtual PHONGBAN PHONGBAN { get; set; }
    }
}
